bmb_creations_output_folder: '{project-root}/_byan-output/bmb-creations'
user_name: Katy
communication_language: Francais
document_output_language: Francais
output_folder: '{project-root}/_byan-output'
platform: copilot
byan_version: 1.0.0
